# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  eslint: arrai/eslint@1.3.0
jobs:
  eslint:
    parameters:
      wd:
        type: string
        default: ~/project
      files:
        type: string
        default: lib/**
      executor:
        type: executor
        default: v8
      config:
        description: "Any additional configuration steps."
        type: steps
        default: []
    executor: <<parameters.executor>>
    steps:
      - checkout
      - utils/add_ssh_config
      - run:
          name: Install additional OS packages
          command: sudo apt-get install rsync
      - run:
          name: Install the latest eslint
          command: sudo npm install -g eslint
      - steps: <<parameters.config>>
      - run:
          name: Run eslint
          command: |
            cd <<parameters.wd>>
            eslint --color <<parameters.files>> | tee ~/lint
      - utils/make_status_shield:
          when: on_fail
          status: errors
          color: red
          logo: eslint
      - run:
          name: Check if we had any warnings
          when: always
          command: test ! -s ~/lint
      - utils/make_status_shield:
          when: always
          status: warnings
          color: orange
          logo: eslint
          preserve: true
      - utils/make_status_shield:
          when: on_success
          status: passed
          color: brightgreen
          logo: eslint
      - utils/rsync_file:
          when: always
          file: ~/status.svg
          remote_file: $CIRCLE_BRANCH.$CIRCLE_JOB.svg
          host: docs
executors:
  v8:
    environment:
        LANG: en_US.UTF-8
    docker:
     - image: circleci/node:8-buster
  v10:
    environment:
        LANG: en_US.UTF-8
    docker:
     - image: circleci/node:10-buster
  v12:
    environment:
        LANG: en_US.UTF-8
    docker:
     - image: circleci/node:12-buster



  # ######################################
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: eslint
